<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $subject }}</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #111;">
    <h2 style="margin-bottom: 0.25rem;">New Support Request</h2>
    <p style="margin-top: 0; color: #555;">{{ $subject }}</p>

    <hr style="margin: 1rem 0; border: none; border-top: 1px solid #eee;"/>

    <h3 style="margin-bottom: 0.25rem;">From</h3>
    <p style="margin-top: 0;">
        <strong>Name:</strong> {{ $name }}<br>
        <strong>Email:</strong> {{ $email }}<br>
        @if(!empty($phone))
        <strong>Phone:</strong> {{ $phone }}<br>
        @endif
    </p>

    <h3 style="margin-bottom: 0.25rem;">Message</h3>
    <p style="white-space: pre-wrap;">{{ $content }}</p>

    <hr style="margin: 1rem 0; border: none; border-top: 1px solid #eee;"/>
    <p style="color: #777; font-size: 12px;">
        This email was generated by the Ishakiro Job Solution support form.
    </p>
</body>
</html>
